# Generated by Django 6.0.6 on 2026-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_driverprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор'), ('dispatcher', 'Логист'), ('driver', 'Водитель')], default='client', max_length=20),
        ),
    ]
