# Generated by Django 6.0.6 on 2026-06-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_address', models.TextField(verbose_name='Адрес погрузки')),
                ('unloading_address', models.TextField(verbose_name='Адрес выгрузки')),
                ('loading_lat', models.FloatField(blank=True, null=True, verbose_name='Широта погрузки')),
                ('loading_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота погрузки')),
                ('unloading_lat', models.FloatField(blank=True, null=True, verbose_name='Широта выгрузки')),
                ('unloading_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота выгрузки')),
                ('distance_km', models.FloatField(default=0.0, verbose_name='Расстояние (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'unique_together': {('loading_address', 'unloading_address')},
            },
        ),
    ]
