# Generated by Django 6.0.6 on 2026-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние (км)'),
        ),
    ]
