# Generated by Django 6.0.6 on 2026-06-29 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('body_type', models.CharField(choices=[('tent', 'Тент'), ('ref', 'Рефрижератор')], max_length=20)),
                ('capacity', models.FloatField(help_text='Грузоподъемность в тоннах')),
                ('base_rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
        ),
    ]
