# Generated by Django 6.0.6 on 2026-07-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В пути'), ('completed', 'Завершен')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
